steps:
## restore cache
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gsutil cp -r gs://mark-build-cache/gradle .gradle || true

## build
- name: java:8
  env: ['GRADLE_USER_HOME=.gradle']
  entrypoint: 'bash'
  args: ['-c', './gradlew --no-daemon build']

## store cache
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gsutil cp -r .gradle gs://mark-build-cache/gradle .gradle

- name: gcr.io/cloud-builders/docker
  args: ['build',
    '--tag', 'asia.gcr.io/$PROJECT_ID/kotlin-test:$SHORT_SHA',
    '--tag', 'asia.gcr.io/$PROJECT_ID/kotlin-test:latest',
    '.' ]

images:
  - asia.gcr.io/$PROJECT_ID/kotlin-test:$SHORT_SHA
  - asia.gcr.io/$PROJECT_ID/kotlin-test:latest
