steps:
- name: alpine
  args: ['mkdir', '.gradle']

#- name: gcr.io/cloud-builders/gsutil
#  args: ['rsync', '-r', 'gs://gradle_cache/kotlin_demo/', '.gradle/']
#  args: ['cp', '-r', 'gs://gradle_cache/kotlin_demo', '.gradle']

- name: java:8
  env: ['GRADLE_USER_HOME=.gradle']
  entrypoint: 'bash'
  args: ['-c', './gradlew --no-daemon build']

- name: java:8
  entrypoint: 'bash'
  args: ['-c', 'ls -al .gradle; ls -al .gradle/caches']

#- name: gcr.io/cloud-builders/gsutil
#  args: ['rsync', '-d', '-r', '.gradle/', 'gs://gradle_cache/kotlin_demo/']
#  args: ['cp', '-r', '.gradle', 'gs://gradle_cache/kotlin_demo']

- name: gcr.io/cloud-builders/docker
  args: ['build',
    '--tag', 'asia.gcr.io/$PROJECT_ID/kotlin-demo:$SHORT_SHA',
    '--tag', 'asia.gcr.io/$PROJECT_ID/kotlin-demo:latest',
    '.' ]

images:
- asia.gcr.io/$PROJECT_ID/kotlin-demo:$SHORT_SHA
- asia.gcr.io/$PROJECT_ID/kotlin-demo:latest
