steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'gs://gradle_cache/kotlin_demo', 'gradle/cache']

#- name: gcr.io/cloud-builders/gradle
#  env: ['GRADLE_USER_HOME=/tmp/gradle']
#  args: ['--no-daemon', 'build']
- name: java:8
  env: ['GRADLE_USER_HOME=gradle']
  entrypoint: 'bash'
  args: ['-c', './gradlew --no-daemon build']

- name: java:8
  env: ['GRADLE_USER_HOME=gradle']
  entrypoint: 'bash'
  args: ['-c', 'ls -al gradle; ls -al gradle/cache']

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'gradle/cache', 'gs://gradle_cache/kotlin_demo']

- name: gcr.io/cloud-builders/docker
  args: ['build',
    '--tag', 'gcr.io/$PROJECT_ID/kotlin-demo:$SHORT_SHA',
    '--tag', 'gcr.io/$PROJECT_ID/kotlin-demo:latest',
    '.' ]

images:
- gcr.io/$PROJECT_ID/kotlin-demo:$SHORT_SHA
- gcr.io/$PROJECT_ID/kotlin-demo:latest
